name: tec
description: "For the assessment of the Flutter developer position at TEC."
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  dio: ^5.9.1
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.8
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  persistent_header_adaptive: ^2.1.3
  go_router: ^16.1.0
  flutter_native_splash: ^2.4.0
  geolocator: ^13.0.4
  toastification: ^3.0.3
  collection: ^1.19.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: LineSeed
      fonts:
        - asset: assets/fonts/LineSeedSans_A_Th.ttf
          weight: 100
        - asset: assets/fonts/LineSeedSans_A_Rg.ttf
          weight: 400
        - asset: assets/fonts/LineSeedSans_A_Bd.ttf
          weight: 700
        - asset: assets/fonts/LineSeedSans_A_XBd.ttf
          weight: 800
        - asset: assets/fonts/LineSeedSans_A_He.ttf
          weight: 900


flutter_native_splash:
  color: "#002E5D" 
  image: assets/images/splash_logo.png 
  ios : true
  web: false
  android: false
